--ASSIGN PROFILE MEMBERS TO THE CORSPONDING TABLE SPACE
-----------------------------------------------------------
-----------------------------------------------------------

ALTER USER "developer" TEMPORARY TABLESPACE temp1;

ALTER USER "accountant" TEMPORARY TABLESPACE temp1;

ALTER USER "data_analyst" TEMPORARY TABLESPACE temp1;

ALTER USER "customer" TEMPORARY TABLESPACE temp2;

ALTER USER "author"  TEMPORARY TABLESPACE temp2;

ALTER USER "publisher" TEMPORARY TABLESPACE temp2;

ALTER USER "OWNER" TEMPORARY TABLESPACE temp3;

ALTER USER "SALES_MANAGER" TEMPORARY TABLESPACE temp3;

ALTER USER "WAREHOUSE_MANAGER" TEMPORARY TABLESPACE temp3;

ALTER USER "TEAM_LEAD_DEVELOPER" TEMPORARY TABLESPACE temp3;

ALTER USER "DBA1" TEMPORARY TABLESPACE temp4;

ALTER USER "DBA2" TEMPORARY TABLESPACE temp4;