--CREATE USERS
-----------------------------------
-----------------------------------

CREATE USER BSTORE IDENTIFIED BY BSTORE;  --********SCHEMA OWNER********

--CREATE USER "OWNER" PROFILE "MANAGERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE OWNER;

CREATE USER "TEAM_LEAD_DEVELOPER" PROFILE "MANAGERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE TEAM_LEAD_DEVELOPER;

CREATE USER "WAREHOUSE_MANAGER" PROFILE "MANAGERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE WAREHOUSE_MANAGER;

CREATE USER "SALES_MANAGER" PROFILE "MANAGERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE SALES_MANAGER;

CREATE USER "DEVELOPER" PROFILE "EMPLOYEES" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE DEVELOPER;

CREATE USER "ACCOUNTANT" PROFILE "EMPLOYEES" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE ACCOUNTANT;

CREATE USER "DATA_ANALYST" PROFILE "EMPLOYEES" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE DATA_ANALYST;

CREATE USER "CUSTOMER" PROFILE "USERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE CUSTOMER;

CREATE USER "AUTHOR" PROFILE "USERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE AUTHOR;

CREATE USER "PUBLISHER" PROFILE "USERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE PUBLISHER;

CREATE USER "DBA1" PROFILE "DBAS" IDENTIFIED BY "dba" ACCOUNT UNLOCK;CREATE ROLE DBA1;

CREATE USER "DBA2" PROFILE "DBAS" IDENTIFIED BY "dba" ACCOUNT UNLOCK;CREATE ROLE DBA2;
