--CREATE USERS
-----------------------------------
-----------------------------------

CREATE USER BSTORE IDENTIFIED BY BSTORE;  --********SCHEMA OWNER********

CREATE USER "OWNER" PROFILE "MANAGERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE OWNER;

CREATE USER "TEAM_LEAD_DEVELOPER" PROFILE "MANAGERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE TEAM_LEAD_DEVELOPER;

CREATE USER "WAREHOUSE_MANAGER" PROFILE "MANAGERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE WAREHOUSE_MANAGER;

CREATE USER "SALES_MANAGER" PROFILE "MANAGERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE SALES_MANAGER;

CREATE USER "developer" PROFILE "EMPLOYEES" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE developer;

CREATE USER "accountant" PROFILE "EMPLOYEES" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE accountant;

CREATE USER "data_analyst" PROFILE "EMPLOYEES" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE data_analyst;

CREATE USER "customer" PROFILE "USERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE customer;

CREATE USER "author" PROFILE "USERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE author;

CREATE USER "publisher" PROFILE "USERS" IDENTIFIED BY "password" ACCOUNT UNLOCK;CREATE ROLE publisher;

CREATE USER "DBA1" PROFILE "DBAS" IDENTIFIED BY "dba" ACCOUNT UNLOCK;CREATE ROLE DBA1;

CREATE USER "DBA2" PROFILE "DBAS" IDENTIFIED BY "dba" ACCOUNT UNLOCK;CREATE ROLE DBA2;