--GIVE PRIVILLAGES
--------------------------
--------------------------

---------------------------
---BSTORE SCHEMA OWNER
---------------------------
GRANT "CONNECT","RESOURCE" TO "BSTORE";
GRANT CREATE VIEW TO BSTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.author TO BSTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.PUBLISHER TO BSTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.BOOK TO BSTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.WAREHOUSE TO BSTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.WAREHOUSE_BOOK TO BSTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.CUSTOMER TO BSTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.SHOPPINGBASKET_BOOK TO BSTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.SHOPPINGBASKET TO BSTORE;
GRANT CREATE CLUSTER TO BSTORE;

--ALTER USER BSTORE QUOTA UNLIMITED ON  ContentCreator;
--ALTER USER BSTORE QUOTA UNLIMITED ON sales ;
--ALTER USER BSTORE QUOTA UNLIMITED ON BOOK ;
--ALTER USER BSTORE QUOTA UNLIMITED ON WAREHOUSE ;
--======================================================================================--

---------------
--DBAs
---------------
GRANT "CONNECT","RESOURCE",SYSDBA TO "DBA1";
GRANT "CONNECT","RESOURCE",DBA TO "DBA2";
--===========================================================================================--

-----------------------
--WAREHOUS MANAGER
-----------------------
GRANT "CONNECT","RESOURCE" TO  "WAREHOUSE_MANAGER";
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.BOOK TO "WAREHOUSE_MANAGER";
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.WAREHOUSE TO "WAREHOUSE_MANAGER";
GRANT SELECT, INSERT, UPDATE, DELETE ON BSTORE.WAREHOUSE_BOOK TO "WAREHOUSE_MANAGER";

ALTER USER "WAREHOUSE_MANAGER" QUOTA 29M ON BOOK ;   ---29mb
ALTER USER "WAREHOUSE_MANAGER" QUOTA 52M ON WAREHOUSE ;  ---52mb
--===================================================================================================--

----------------------
/*OWNER
-----------------------
GRANT "CONNECT","RESOURCE" TO "OWNER";
GRANT SELECT, INSERT, UPDATE ON BSTORE.author TO "OWNER";
GRANT SELECT, INSERT, UPDATE ON BSTORE.PUBLISHER TO "OWNER";
GRANT SELECT, INSERT, UPDATE ON BSTORE.BOOK TO "OWNER";
GRANT SELECT, INSERT, UPDATE ON BSTORE.WAREHOUSE TO "OWNER";
GRANT SELECT, INSERT, UPDATE ON BSTORE.WAREHOUSE_BOOK TO "OWNER";
GRANT SELECT, INSERT, UPDATE ON BSTORE.CUSTOMER TO "OWNER";
GRANT SELECT, INSERT, UPDATE ON BSTORE.SHOPPINGBASKET_BOOK TO "OWNER";
GRANT SELECT, INSERT, UPDATE ON BSTORE.SHOPPINGBASKET TO "OWNER";

ALTER USER "OWNER" QUOTA UNLIMITED ON  ContentCreator;
ALTER USER "OWNER" QUOTA UNLIMITED ON sales ;
ALTER USER "OWNER" QUOTA UNLIMITED ON BOOK ;
ALTER USER "OWNER" QUOTA UNLIMITED ON WAREHOUSE ;*/
--======================================================================================================--

--------------------
--SALES MANAGER
--------------------
GRANT "CONNECT","RESOURCE" TO "SALES_MANAGER";
GRANT SELECT ON BSTORE.author TO "SALES_MANAGER";
GRANT SELECT ON BSTORE.PUBLISHER TO "SALES_MANAGER";
GRANT SELECT ON BSTORE.BOOK TO "SALES_MANAGER";
GRANT SELECT ON BSTORE.CUSTOMER TO "SALES_MANAGER";
GRANT SELECT ON BSTORE.SHOPPINGBASKET_BOOK TO "SALES_MANAGER";
--============================================================================================================--

-------------------------
--TEAM LEAD DEVELOPER
-------------------------
GRANT "CONNECT","RESOURCE" TO "TEAM_LEAD_DEVELOPER";
GRANT SELECT ON BSTORE.author TO "TEAM_LEAD_DEVELOPER";
GRANT SELECT ON BSTORE.PUBLISHER TO "TEAM_LEAD_DEVELOPER";
GRANT SELECT ON BSTORE.BOOK TO "TEAM_LEAD_DEVELOPER";
GRANT SELECT ON BSTORE.CUSTOMER TO "TEAM_LEAD_DEVELOPER";
GRANT SELECT ON BSTORE.SHOPPINGBASKET_BOOK TO "TEAM_LEAD_DEVELOPER";
GRANT SELECT ON BSTORE.WAREHOUSE TO "TEAM_LEAD_DEVELOPER";
GRANT SELECT ON BSTORE.WAREHOUSE_BOOK TO "TEAM_LEAD_DEVELOPER";
GRANT SELECT ON BSTORE.SHOPPINGBASKET TO "TEAM_LEAD_DEVELOPER";
--===============================================================================================================--

--------------------
--DEVELOPER
--------------------
GRANT "CONNECT","RESOURCE" TO "DEVELOPER";
GRANT SELECT ON BSTORE.author TO "DEVELOPER";
GRANT SELECT ON BSTORE.PUBLISHER TO "DEVELOPER";
GRANT SELECT ON BSTORE.BOOK TO "DEVELOPER";
GRANT SELECT ON BSTORE.CUSTOMER TO "DEVELOPER";
GRANT SELECT ON BSTORE.SHOPPINGBASKET_BOOK TO "DEVELOPER";
GRANT SELECT ON BSTORE.WAREHOUSE TO "DEVELOPER";
GRANT SELECT ON BSTORE.WAREHOUSE_BOOK TO "DEVELOPER";
GRANT SELECT ON BSTORE.SHOPPINGBASKET TO "DEVELOPER";
--====================================================================================================================--

---------------------
--data analyist
---------------------
GRANT "CONNECT","RESOURCE" TO "DATA_ANALYST";
GRANT SELECT ON BSTORE.author TO "DATA_ANALYST";
GRANT SELECT ON BSTORE.PUBLISHER TO "DATA_ANALYST";
GRANT SELECT ON BSTORE.BOOK TO "DATA_ANALYST";
GRANT SELECT ON BSTORE.CUSTOMER TO "DATA_ANALYST";
GRANT SELECT ON BSTORE.SHOPPINGBASKET_BOOK TO "DATA_ANALYST";
GRANT SELECT ON BSTORE.WAREHOUSE TO "DATA_ANALYST";
GRANT SELECT ON BSTORE.WAREHOUSE_BOOK TO "DATA_ANALYST";
GRANT SELECT ON BSTORE.SHOPPINGBASKET TO "DATA_ANALYST";
--==========================================================================================================================--

---------------
--ACCOUNTANT
----------------
GRANT "CONNECT","RESOURCE" TO "ACCOUNTANT";
GRANT SELECT ON BSTORE.author TO "ACCOUNTANT";
GRANT SELECT ON BSTORE.PUBLISHER TO "ACCOUNTANT";
GRANT SELECT ON BSTORE.BOOK TO "ACCOUNTANT";
GRANT SELECT ON BSTORE.CUSTOMER TO "ACCOUNTANT";
GRANT SELECT ON BSTORE.SHOPPINGBASKET_BOOK TO "ACCOUNTANT";
GRANT SELECT ON BSTORE.WAREHOUSE TO "ACCOUNTANT";
GRANT SELECT ON BSTORE.WAREHOUSE_BOOK TO "ACCOUNTANT";
GRANT SELECT ON BSTORE.SHOPPINGBASKET TO "ACCOUNTANT";
--==============================================================================================================================--

-------------
--CUSTOMER
-------------
GRANT "CONNECT","RESOURCE" TO "CUSTOMER";
GRANT INSERT ON BSTORE.CUSTOMER TO "CUSTOMER";

ALTER USER "CUSTOMER" QUOTA 2k ON SALES ;   ---1020B---->2kb
--===================================================================================================================================--

---------------
--publisher
---------------
GRANT "CONNECT","RESOURCE" TO "PUBLISHER";
GRANT INSERT ON BSTORE.publisher TO "PUBLISHER";

ALTER USER "PUBLISHER" QUOTA 2k ON contentcreator ;    ---1026B---->2kb
--===================================================================================================================================--

------------
--author
------------
GRANT "CONNECT","RESOURCE" TO "AUTHOR";
GRANT INSERT ON BSTORE.author TO "AUTHOR";

ALTER USER "AUTHOR" QUOTA 2k ON contentcreator ;    ---771B---->1kb

